var j =0;
var data = [
	['AL', 'Alabama', '54', '46', 'Abortion'], 
	['AK', 'Alaska', '48', '52', 'Second Amendment (gun control)'], 
	['AZ', 'Arizona', '34', '66', 'Environment'], 
	['AR', 'Arkansas', '56', '44', 'Immigration Reform'], 
	['CA', 'California', '34', '66', 'Economy (tax reform)'], 
	['CO', 'Colorado', '28', '72', 'Surveillance'], 
	['CT', 'Connecticut', '32', '68', 'Foreign Policy'], 
	['DE', 'Delaware', '41', '59', 'Abortion'], 
	['DC', 'District of Columbia', '13', '87', 'Second Amendment (gun control)'], 
	['FL', 'Florida', '55', '45', 'Environment'], 
	['GA', 'Georgia', '67', '33', 'Immigration Reform'], 
	['HI', 'Hawaii', '42', '58', 'Abortion'], 
	['ID', 'Idaho', '41', '59', 'Second Amendment (gun control)'], 
	['IL', 'Illinois', '48', '52', 'Environment'], 
	['IN', 'Indiana', '42', '58', 'Immigration Reform'], 
	['IA', 'Iowa', '47', '53', 'Economy (tax reform)'], 
	['KS', 'Kansas', '65', '35', 'Surveillance'], 
	['KY', 'Kentucky', '69', '31', 'Foreign Policy'], 
	['LA', 'Louisiana', '73', '27', 'Abortion'], 
	['ME', 'Maine', '18', '82', 'Second Amendment (gun control)'], 
	['MD', 'Maryland', '34', '66', 'Environment'], 
	['MA', 'Massachusetts', '41', '59', 'Immigration Reform'], 
	['MI', 'Michigan', '51', '49', 'Economy (tax reform)'], 
	['MN', 'Minnesota', '50', '50', 'Surveillance'], 
	['MS', 'Mississippi', '74', '26', 'Foreign Policy'], 
	['MO', 'Missouri', '59', '41', 'Abortion'], 
	['MT', 'Montana', '45', '55', 'Second Amendment (gun control)'], 
	['NE', 'Nebraska', '65', '35', 'Environment'], 
	['NV', 'Nevada', '33', '67', 'Immigration Reform'], 
	['NH', 'New Hampshire', '24', '76', 'Economy (tax reform)'], 
	['NJ', 'New Jersey', '56', '44', 'Surveillance'], 
	['NM', 'New Mexico', '64', '46', 'Foreign Policy'], 
	['NY', 'New York', '34', '66', 'Abortion'], 
	['NC', 'North Carolina', '55', '45', 'Second Amendment (gun control)'], 
	['ND', 'North Dakota', '68', '32', 'Environment'], 
	['OH', 'Ohio', '64', '36', 'Immigration', 'Reform'], 
	['OK', 'Oklahoma', '75', '25', 'Economy (tax reform)'], 
	['OR', 'Oregon', '16', '84', 'Surveillance'], 
	['PA', 'Pennsylvania', '32', '68', 'Foreign', 'Policy'], 
	['RI', 'Rhode Island', '24', '76', 'Abortion'], 
	['SC', 'South Carolina', '70', '30', 'Second Amendment (gun control)'], 
	['SD', 'South Dakota', '44', '56', 'Environment'], 
	['TN', 'Tennessee', '74', '26', 'Immigration Reform'], 
	['TX', 'Texas', '77', '23', 'Economy (tax reform)'], 
	['UT', 'Utah', '43', '57', 'Surveillance'], 
	['VT', 'Vermont', '20', '80', 'Foreign Policy'], 
	['VA', 'Virginia', '39', '61', 'Abortion'], 
	['WA', 'Washington', '21', '79', 'Second Amendment (gun control)'], 
	['WV', 'West Virginia', '57', '43', 'Environment'], 
	['WI', 'Wisconsin', '47', '53', 'Immigration Reform'], 
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)']
]
var positive_data = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)'],
]

var women = [
	['AL', 'Alabama', '46', '46', 'Abortion'], ['AK', 'Alaska', '56', '52', 'Second Amendment (gun control)'], ['AZ', 'Arizona', '45', '66', 'Environment'], ['AR', 'Arkansas', '55', '44', 'Immigration Reform'], ['CA', 'California', '74', '66', 'Economy (tax reform)'], ['CO', 'Colorado', '67', '72', 'Surveillance'], ['CT', 'Connecticut', '66', '68', 'Foreign Policy'], ['DE', 'Delaware', '55', '59', 'Abortion'], ['DC', 'District of Columbia', '64', '87', 'Second Amendment (gun control)'], ['FL', 'Florida', '40', '4', 'Environment'], ['GA', 'Georgia', '43', '26', 'Immigration Reform'], ['HI', 'Hawaii', '54', '41', 'Abortion'], ['ID', 'Idaho', '58', '48', 'Second Amendment (gun control)'], ['IL', 'Illinois', '51', '37', 'Environment'], ['IN', 'Indiana', '54', '36', 'Immigration Reform'], ['IA', 'Iowa', '53', '41', 'Economy (tax reform)'], ['KS', 'Kansas', '46', '32', 'Surveillance'], ['KY', 'Kentucky', '44', '26', 'Foreign Policy'], ['LA', 'Louisiana', '47', '21', 'Abortion'], ['ME', 'Maine', '75', '12', 'Second Amendment (gun control)'], ['MD', 'Maryland', '75', '10', 'Environment'], ['MA', 'Massachusetts', '68', '20', 'Immigration Reform'], ['MI', 'Michigan', '50', '10', 'Economy (tax reform)'], ['MN', 'Minnesota', '46', '40', 'Surveillance'], ['MS', 'Mississippi', '38', '23', 'Foreign Policy'], ['MO', 'Missouri', '40', '35', 'Abortion'], ['MT', 'Montana', '48', '17', 'Second Amendment (gun control)'], ['NE', 'Nebraska', '39', '28', 'Environment'], ['NV', 'Nevada', '56', '15', 'Immigration Reform'], ['NH', 'New Hampshire', '65', '7', 'Economy (tax reform)'], ['NJ', 'New Jersey', '44', '6', 'Surveillance'], ['NM', 'New Mexico', '50', '7', 'Foreign Policy'], ['NY', 'New York', '77', '45', 'Abortion'], ['NC', 'North Carolina', '43', '10', 'Second Amendment (gun control)'], ['ND', 'North Dakota', '44', '14', 'Environment'], ['OH', 'Ohio', '53', '28', 'Immigration', 'Reform'], ['OK', 'Oklahoma', '43', '47', 'Economy (tax reform)'], ['OR', 'Oregon', '68', '14', 'Surveillance'], ['PA', 'Pennsylvania', '65', '46', 'Foreign', 'Policy'], ['RI', 'Rhode Island', '65', '28', 'Abortion'], ['SC', 'South Carolina', '39', '30', 'Second Amendment (gun control)'], ['SD', 'South Dakota', '43', '1', 'Environment'], ['TN', 'Tennessee', '44', '30', 'Immigration Reform'], ['TX', 'Texas', '41', '37', 'Economy (tax reform)'], ['UT', 'Utah', '47', '23', 'Surveillance'], ['VT', 'Vermont', '65', '21', 'Foreign Policy'], ['VA', 'Virginia', '54', '36', 'Abortion'], ['WA', 'Washington', '80', '25', 'Second Amendment (gun control)'], ['WV', 'West Virginia', '41', '16', 'Environment'], ['WI', 'Wisconsin', '48', '27', 'Immigration Reform'], ['WY', 'Wyoming', '47', '53', 'Economy (tax reform)']
]
var men = [
	['AL', 'Alabama', '46', '54', 'Abortion'], ['AK', 'Alaska', '56', '44', 'Second Amendment (gun control)'], ['AZ', 'Arizona', '45', '55', 'Environment'], ['AR', 'Arkansas', '55', '45', 'Immigration Reform'], ['CA', 'California', '74', '26', 'Economy (tax reform)'], ['CO', 'Colorado', '67', '33', 'Surveillance'], ['CT', 'Connecticut', '66', '34', 'Foreign Policy'], ['DE', 'Delaware', '55', '45', 'Abortion'], ['DC', 'District of Columbia', '64', '36', 'Second Amendment (gun control)'], ['FL', 'Florida', '40', '60', 'Environment'], ['GA', 'Georgia', '43', '57', 'Immigration Reform'], ['HI', 'Hawaii', '54', '46', 'Abortion'], ['ID', 'Idaho', '58', '42', 'Second Amendment (gun control)'], ['IL', 'Illinois', '51', '49', 'Environment'], ['IN', 'Indiana', '54', '46', 'Immigration Reform'], ['IA', 'Iowa', '53', '47', 'Economy (tax reform)'], ['KS', 'Kansas', '46', '54', 'Surveillance'], ['KY', 'Kentucky', '44', '56', 'Foreign Policy'], ['LA', 'Louisiana', '47', '53', 'Abortion'], ['ME', 'Maine', '75', '25', 'Second Amendment (gun control)'], ['MD', 'Maryland', '75', '25', 'Environment'], ['MA', 'Massachusetts', '68', '32', 'Immigration Reform'], ['MI', 'Michigan', '50', '50', 'Economy (tax reform)'], ['MN', 'Minnesota', '46', '54', 'Surveillance'], ['MS', 'Mississippi', '38', '62', 'Foreign Policy'], ['MO', 'Missouri', '40', '60', 'Abortion'], ['MT', 'Montana', '48', '52', 'Second Amendment (gun control)'], ['NE', 'Nebraska', '39', '61', 'Environment'], ['NV', 'Nevada', '56', '44', 'Immigration Reform'], ['NH', 'New Hampshire', '65', '35', 'Economy (tax reform)'], ['NJ', 'New Jersey', '44', '56', 'Surveillance'], ['NM', 'New Mexico', '50', '50', 'Foreign Policy'], ['NY', 'New York', '77', '23', 'Abortion'], ['NC', 'North Carolina', '43', '57', 'Second Amendment (gun control)'], ['ND', 'North Dakota', '44', '56', 'Environment'], ['OH', 'Ohio', '53', '47', 'Immigration', 'Reform'], ['OK', 'Oklahoma', '43', '57', 'Economy (tax reform)'], ['OR', 'Oregon', '68', '32', 'Surveillance'], ['PA', 'Pennsylvania', '65', '35', 'Foreign', 'Policy'], ['RI', 'Rhode Island', '65', '35', 'Abortion'], ['SC', 'South Carolina', '39', '61', 'Second Amendment (gun control)'], ['SD', 'South Dakota', '43', '57', 'Environment'], ['TN', 'Tennessee', '44', '56', 'Immigration Reform'], ['TX', 'Texas', '41', '59', 'Economy (tax reform)'], ['UT', 'Utah', '47', '53', 'Surveillance'], ['VT', 'Vermont', '65', '35', 'Foreign Policy'], ['VA', 'Virginia', '54', '46', 'Abortion'], ['WA', 'Washington', '80', '20', 'Second Amendment (gun control)'], ['WV', 'West Virginia', '41', '59', 'Environment'], ['WI', 'Wisconsin', '48', '52', 'Immigration Reform'], ['WY', 'Wyoming', '47', '14', 'Economy (tax reform)']
]
var young = [
	['AL', 'Alabama', '54', '46', 'Abortion'], ['AK', 'Alaska', '36', '52', 'Second Amendment (gun control)'], ['AZ', 'Arizona', '47', '66', 'Environment'], ['AR', 'Arkansas', '37', '44', 'Immigration Reform'], ['CA', 'California', '18', '66', 'Economy (tax reform)'], ['CO', 'Colorado', '25', '72', 'Surveillance'], ['CT', 'Connecticut', '34', '68', 'Foreign Policy'], ['DE', 'Delaware', '37', '59', 'Abortion'], ['DC', 'District of Columbia', '28', '87', 'Second Amendment (gun control)'], ['FL', 'Florida', '52', '4', 'Environment'], ['GA', 'Georgia', '49', '26', 'Immigration Reform'], ['HI', 'Hawaii', '38', '41', 'Abortion'], ['ID', 'Idaho', '42', '48', 'Second Amendment (gun control)'], ['IL', 'Illinois', '41', '37', 'Environment'], ['IN', 'Indiana', '38', '36', 'Immigration Reform'], ['IA', 'Iowa', '39', '41', 'Economy (tax reform)'], ['KS', 'Kansas', '46', '32', 'Surveillance'], ['KY', 'Kentucky', '48', '26', 'Foreign Policy'], ['LA', 'Louisiana', '53', '21', 'Abortion'], ['ME', 'Maine', '17', '12', 'Second Amendment (gun control)'], ['MD', 'Maryland', '17', '10', 'Environment'], ['MA', 'Massachusetts', '24', '20', 'Immigration Reform'], ['MI', 'Michigan', '42', '10', 'Economy (tax reform)'], ['MN', 'Minnesota', '46', '40', 'Surveillance'], ['MS', 'Mississippi', '62', '23', 'Foreign Policy'], ['MO', 'Missouri', '52', '35', 'Abortion'], ['MT', 'Montana', '44', '17', 'Second Amendment (gun control)'], ['NE', 'Nebraska', '53', '28', 'Environment'], ['NV', 'Nevada', '36', '15', 'Immigration Reform'], ['NH', 'New Hampshire', '27', '7', 'Economy (tax reform)'], ['NJ', 'New Jersey', '56', '6', 'Surveillance'], ['NM', 'New Mexico', '42', '7', 'Foreign Policy'], ['NY', 'New York', '15', '45', 'Abortion'], ['NC', 'North Carolina', '49', '10', 'Second Amendment (gun control)'], ['ND', 'North Dakota', '48', '14', 'Environment'], ['OH', 'Ohio', '39', '28', 'Immigration', 'Reform'], ['OK', 'Oklahoma', '57', '47', 'Economy (tax reform)'], ['OR', 'Oregon', '24', '14', 'Surveillance'], ['PA', 'Pennsylvania', '27', '46', 'Foreign', 'Policy'], ['RI', 'Rhode Island', '27', '28', 'Abortion'], ['SC', 'South Carolina', '53', '30', 'Second Amendment (gun control)'], ['SD', 'South Dakota', '49', '1', 'Environment'], ['TN', 'Tennessee', '56', '30', 'Immigration Reform'], ['TX', 'Texas', '51', '37', 'Economy (tax reform)'], ['UT', 'Utah', '45', '23', 'Surveillance'], ['VT', 'Vermont', '27', '21', 'Foreign Policy'], ['VA', 'Virginia', '38', '36', 'Abortion'], ['WA', 'Washington', '12', '25', 'Second Amendment (gun control)'], ['WV', 'West Virginia', '59', '16', 'Environment'], ['WI', 'Wisconsin', '44', '27', 'Immigration Reform'], ['WY', 'Wyoming', '47', '14', 'Economy (tax reform)']
]
var positive_data = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)'],
]
var west = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)'],
]
var midwest = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)'],
]
var nort_east = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)'],
]

var south = [
	['AL', 'Alabama', '47', '13', 'Abortion'],
	['AK', 'Alaska', '22', '11', 'Second Amendment (gun control)'],
	['AZ', 'Arizona', '24', '43', 'Environment'],
	['AR', 'Arkansas', '24', '19', 'Immigration Reform'],
	['CA', 'California', '22', '31', 'Economy (tax reform)'],
	['CO', 'Colorado', '44', '19', 'Surveillance'],
	['CT', 'Connecticut', '32', '27', 'Foreign Policy'],
	['DE', 'Delaware', '24', '18', 'Abortion'],
	['DC', 'District of Columbia', '13', '22', 'Second Amendment (gun control)'],
	['FL', 'Florida', '47', '4', 'Environment'],
	['GA', 'Georgia', '31', '26', 'Immigration Reform'],
	['HI', 'Hawaii', '21', '41', 'Abortion'],
	['ID', 'Idaho', '20', '48', 'Second Amendment (gun control)'],
	['IL', 'Illinois', '21', '37', 'Environment'],
	['IN', 'Indiana', '18', '36', 'Immigration Reform'],
	['IA', 'Iowa', '23', '41', 'Economy (tax reform)'],
	['KS', 'Kansas', '44', '32', 'Surveillance'],
	['KY', 'Kentucky', '40', '26', 'Foreign Policy'],
	['LA', 'Louisiana', '30', '21', 'Abortion'],
	['ME', 'Maine', '33', '12', 'Second Amendment (gun control)'],
	['MD', 'Maryland', '31', '10', 'Environment'],
	['MA', 'Massachusetts', '19', '20', 'Immigration Reform'],
	['MI', 'Michigan', '46', '10', 'Economy (tax reform)'],
	['MN', 'Minnesota', '45', '40', 'Surveillance'],
	['MS', 'Mississippi', '26', '23', 'Foreign Policy'],
	['MO', 'Missouri', '25', '35', 'Abortion'],
	['MT', 'Montana', '6', '17', 'Second Amendment (gun control)'],
	['NE', 'Nebraska', '39', '28', 'Environment'],
	['NV', 'Nevada', '15', '15', 'Immigration Reform'],
	['NH', 'New Hampshire', '18', '7', 'Economy (tax reform)'],
	['NJ', 'New Jersey', '11', '6', 'Surveillance'],
	['NM', 'New Mexico', '48', '7', 'Foreign Policy'],
	['NY', 'New York', '15', '45', 'Abortion'],
	['NC', 'North Carolina', '29', '10', 'Second Amendment (gun control)'],
	['ND', 'North Dakota', '36', '14', 'Environment'],
	['OH', 'Ohio', '33', '28', 'Immigration', 'Reform'],
	['OK', 'Oklahoma', '40', '47', 'Economy (tax reform)'],
	['OR', 'Oregon', '29', '14', 'Surveillance'],
	['PA', 'Pennsylvania', '9', '46', 'Foreign', 'Policy'],
	['RI', 'Rhode Island', '44', '28', 'Abortion'],
	['SC', 'South Carolina', '45', '30', 'Second Amendment (gun control)'],
	['SD', 'South Dakota', '38', '1', 'Environment'],
	['TN', 'Tennessee', '13', '30', 'Immigration Reform'],
	['TX', 'Texas', '26', '37', 'Economy (tax reform)'],
	['UT', 'Utah', '42', '23', 'Surveillance'],
	['VT', 'Vermont', '22', '21', 'Foreign Policy'],
	['VA', 'Virginia', '14', '36', 'Abortion'],
	['WA', 'Washington', '42', '25', 'Second Amendment (gun control)'],
	['WV', 'West Virginia', '41', '16', 'Environment'],
	['WI', 'Wisconsin', '3', '27', 'Immigration Reform'],
	['WY', 'Wyoming', '47', '14', 'Economy (tax reform)']
]
$(document).ready(function(){
	for (i in data) {
		$("#"+data[i][0]).css("fill","rgb(215, 25, 25)");
		$("#"+data[i][0]).css("opacity", data[i][2]/48);
	}

	$("#positive_tweets").click(function(){
		console.log('hi');
		for (j in positive_data) {
			$("#"+data[j][0]).css("fill","rgb(215, 25, 25)");
			$("#"+data[j][0]).css("opacity", data[j][2]/48);
		}
	});

	$("#negative_tweets").click(function(){
		console.log('hi');
		for (j in positive_data) {
			$("#"+data[j][0]).css("fill","rgb(215, 25, 25)");
			$("#"+data[j][0]).css("opacity", data[j][3]/48);
		}
	});

	$("#women").click(function(){
		console.log('hi');
		for (j in positive_data) {
			$("#"+women[j][0]).css("fill","rgb(215, 25, 25)");
			$("#"+women[j][0]).css("opacity", women[j][2]/48);
		}
	});

	$("#men").click(function(){
		console.log('hi');
		for (j in positive_data) {
			$("#"+men[j][0]).css("fill","rgb(215, 25, 25)");
			$("#"+men[j][0]).css("opacity", men[j][3]/48);
		}
	});

	$("#18-30").click(function(){
		console.log('hi');
		for (j in positive_data) {
			$("#"+young[j][0]).css("fill","rgb(215, 25, 25)");
			$("#"+young[j][0]).css("opacity", young[j][2]/48);
		}
	});
});